# Cut a release whenever a new tag is pushed to the repo.
name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
        contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Build release archive
        run: git archive --format=tar ${{ github.ref_name }} | gzip -n > googleapis-rules-registry-${{ github.ref_name }}.tar.gz

      - name: Create release
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2.2.1
        with:
          generate_release_notes: true
          fail_on_unmatched_files: true
          files: googleapis-rules-registry-${{ github.ref_name }}.tar.gz
